id: IE18E2EB5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:03:41+00:00'
last_modified: '2022-06-09T07:37:02.808503+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22907
  title: སློབ་གསོ་དོ་དམ་གྱི་སྒྱུ་རྩལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C8D9:
      image_group_id: I1KG22962
      title: Volume 1 of slob gso do dam gyi sgyu rtsal/
      total_pages: 250
      order: 1
      base_file: C8D9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
