id: P007928
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22907
  title: སློབ་གསོ་དོ་དམ་གྱི་སྒྱུ་རྩལ།
  author: ''
  volumes:
    0cea921df44a47a98b072496c481e2bf:
      image_group_id: I1KG22962
      title: ''
      volume_number: 1
      total_pages: 250
ebook_metadata:
  title: སློབ་གསོ་དོ་དམ་གྱི་སྒྱུ་རྩལ།
  author: ''
  sku: P007928
  cover: cover.jpg
  layers:
  - pagination
